tls:
  certificates:
    - certFile: /certs/app.localhost+1.pem
      keyFile:  /certs/app.localhost+1-key.pem

  stores:
    default:
      defaultCertificate:
        certFile: /certs/app.localhost+1.pem
        keyFile:  /certs/app.localhost+1-key.pem